export enum Images {
  APP_LOGO_IMAGE = require('./app_logo.png'),
  EMAIL_LOGO_IMAGE = require('./email_logo.png'),
  EYE_HIDE_IMAGE = require('./eye_hide.png'),
  EYE_SHOW_IMAGE = require('./eye_show.png'),
  HEART_IMAGE = require('./heart.png'),
  HEART_FILL_IMAGE = require('./heart_fill.png'),
  HOME_IMAGE = require('./home.png'),
  HOME_OUTLINE_IMAGE = require('./home_outline.png'),
  LOCATION_IMAGE = require('./location.png'),
  LOCK_IMAGE = require('./lock.png'),
  LOGOUT_IMAGE = require('./logout.png'),
  PLACEHOLDER_IMAGE = require('./placeholder.webp'),
  STAR_IMAGE = require('./star.png'),
  STAR_FILL_IMAGE = require('./star_fill.png'),
}
